/**
 * Repositories (Agent B2).
 *
 * These move rows. They do not decide anything.
 *
 * That sentence is the whole design. `authorize()` in `domains/household` is
 * the single place access is decided, and the API tier calls it before it calls
 * anything here. If a repository also checked permissions there would be two
 * rules that could disagree, and the one that disagreed silently would be the
 * one nobody read. What repositories DO enforce is **tenancy**, because that is
 * not a permission question — it is "this row is not yours to see", and it
 * belongs in the WHERE clause of every single query so that forgetting it is
 * impossible rather than merely discouraged.
 *
 * Three conventions:
 *
 *   - Every read takes `householdId` and puts it in the WHERE clause. There is
 *     no `findById(id)` anywhere in this file, on purpose: an id alone is an
 *     invitation to leak across tenants.
 *   - Every write that produces something searchable pushes a `SearchDocument`
 *     in the SAME transaction. Search deliberately cannot read domain tables
 *     (Agent K's design), so an un-pushed row is an invisible row — and doing it
 *     in the transaction is what stops a crash between the two leaving the index
 *     lying.
 *   - Ids are generated by the database (`gen_random_uuid()`), not by the
 *     caller and not here. The domain modules refuse to invent identity; so
 *     does this layer.
 */

import type { Queryable } from './client.ts';
import {
  toBusiness, toEmployee, toErrand, toEvent, toExpense, toHousehold, toInboxItem,
  toMember, toMovement, toNotification, toProduct, toReminder, toSale, toSchedule,
  toSearchDocument, toShift, toShiftSwap, toShoppingItem, toTimeOff, toAvailability,
  type BusinessRow, type EmployeeRow, type ErrandRow, type EventRow, type ExpenseRow,
  type HouseholdRow, type InboxItemRow, type MemberRow, type MovementRow,
  type NotificationRow, type ProductRow, type ReminderRow, type SaleRow,
  type ScheduleRow, type SearchDocumentRow, type ShiftRow, type ShiftSwapRow,
  type ShoppingItemRow, type TimeOffRow, type AvailabilityRow,
} from './rows.ts';
import type {
  Availability, Business, DomainKey, Employee, Errand, EventRecord, Expense, Household,
  InboxItem, InventoryMovement, Member, Notification, Product, RecurrenceRule, Reminder,
  Role, Sale, Schedule, SearchDocument, SearchEntity, Shift, ShiftSwap, ShoppingItem,
  TimeOffRequest, UUID,
} from '../../lib/contracts/index.ts';

/* ------------------------------------------------------------------ search */

/**
 * Upsert one search document. Called inside the caller's transaction.
 *
 * `on conflict … do update` rather than delete-then-insert so that a re-index
 * of an unchanged row does not briefly make it unfindable.
 */
export async function indexDocument(tx: Queryable, doc: SearchDocument): Promise<void> {
  await tx.query(
    `insert into search_document (entity, id, household_id, title, body, domain, at, member_ids, business_id)
     values ($1,$2,$3,$4,$5,$6,$7,$8,$9)
     on conflict (entity, id) do update set
       household_id = excluded.household_id,
       title        = excluded.title,
       body         = excluded.body,
       domain       = excluded.domain,
       at           = excluded.at,
       member_ids   = excluded.member_ids,
       business_id  = excluded.business_id`,
    [
      doc.entity, doc.id, doc.householdId, doc.title, doc.body ?? null,
      doc.domain ?? null, doc.at ?? null, doc.memberIds ?? null, doc.businessId ?? null,
    ],
  );
}

export async function unindexDocument(tx: Queryable, entity: SearchEntity, id: string): Promise<void> {
  await tx.query(`delete from search_document where entity = $1 and id = $2`, [entity, id]);
}

/**
 * Search, scoped to a household and to the entities the caller may see.
 *
 * Ranking is Postgres `ts_rank_cd` over the weighted vector the trigger
 * maintains, with recency as the tie-break. The permission decision about WHICH
 * entities to pass in belongs to the caller — this function will happily search
 * whatever it is told to, which is precisely why the API tier computes that
 * list from `authorize()` and never from user input.
 */
export async function searchDocuments(
  tx: Queryable,
  householdId: UUID,
  query: string,
  entities: readonly SearchEntity[],
  options: { limit?: number; businessId?: UUID } = {},
): Promise<Array<SearchDocument & { rank: number }>> {
  if (entities.length === 0 || query.trim().length === 0) return [];

  const { rows } = await tx.query<SearchDocumentRow & { rank: number }>(
    `select entity, id, household_id, title, body, domain, at, member_ids, business_id,
            ts_rank_cd(tsv, plainto_tsquery('simple', $2)) as rank
       from search_document
      where household_id = $1
        and entity = any($3::text[])
        and tsv @@ plainto_tsquery('simple', $2)
        and (business_id is null or business_id = $4)
      order by rank desc, at desc nulls last, entity asc, id asc
      limit $5`,
    [householdId, query, entities as string[], options.businessId ?? null, options.limit ?? 20],
  );

  return rows.map((r) => ({ ...toSearchDocument(r), rank: Number(r.rank) }));
}

/* --------------------------------------------------------------- household */

export async function createHousehold(
  tx: Queryable,
  input: { name: string; timezone: string },
): Promise<Household> {
  const { rows } = await tx.query<HouseholdRow>(
    `insert into household (name, timezone) values ($1,$2) returning *`,
    [input.name.trim(), input.timezone],
  );
  return toHousehold(rows[0]!);
}

export async function getHousehold(tx: Queryable, householdId: UUID): Promise<Household | null> {
  const { rows } = await tx.query<HouseholdRow>(`select * from household where id = $1`, [householdId]);
  return rows.length > 0 ? toHousehold(rows[0]!) : null;
}

export async function listMembers(tx: Queryable, householdId: UUID): Promise<Member[]> {
  const { rows } = await tx.query<MemberRow>(
    `select * from member where household_id = $1 order by
       case role when 'owner' then 0 when 'adult' then 1 when 'teen' then 2
                 when 'child' then 3 when 'employee' then 4 else 5 end,
       display_name asc`,
    [householdId],
  );
  return rows.map(toMember);
}

/** The member row for one login in one household — the API tier's actor lookup. */
export async function findMemberForUser(
  tx: Queryable,
  householdId: UUID,
  userId: UUID,
): Promise<Member | null> {
  const { rows } = await tx.query<MemberRow>(
    `select * from member where household_id = $1 and user_id = $2`,
    [householdId, userId],
  );
  return rows.length > 0 ? toMember(rows[0]!) : null;
}

export async function getMember(tx: Queryable, householdId: UUID, memberId: UUID): Promise<Member | null> {
  const { rows } = await tx.query<MemberRow>(
    `select * from member where household_id = $1 and id = $2`,
    [householdId, memberId],
  );
  return rows.length > 0 ? toMember(rows[0]!) : null;
}

/** Every household a login belongs to, for the household switcher. */
export async function listHouseholdsForUser(
  tx: Queryable,
  userId: UUID,
): Promise<Array<{ household: Household; member: Member }>> {
  const { rows } = await tx.query<HouseholdRow & { m_id: string }>(
    `select h.*, m.id as m_id
       from household h join member m on m.household_id = h.id
      where m.user_id = $1 and m.active
      order by h.created_at asc`,
    [userId],
  );
  const out: Array<{ household: Household; member: Member }> = [];
  for (const row of rows) {
    const member = await getMember(tx, row.id, row.m_id);
    if (member !== null) out.push({ household: toHousehold(row), member });
  }
  return out;
}

export async function createMember(
  tx: Queryable,
  input: { householdId: UUID; userId?: UUID | null; displayName: string; role: Role; color?: string },
): Promise<Member> {
  const { rows } = await tx.query<MemberRow>(
    `insert into member (household_id, user_id, display_name, role, color)
     values ($1,$2,$3,$4,coalesce($5,'slate')) returning *`,
    [input.householdId, input.userId ?? null, input.displayName.trim(), input.role, input.color ?? null],
  );
  const member = toMember(rows[0]!);
  await indexDocument(tx, {
    entity: 'member',
    id: member.id,
    householdId: member.householdId,
    title: member.displayName,
    body: member.role,
  });
  return member;
}

export async function updateMember(
  tx: Queryable,
  householdId: UUID,
  memberId: UUID,
  patch: { displayName?: string; role?: Role; color?: string; active?: boolean },
): Promise<Member | null> {
  const { rows } = await tx.query<MemberRow>(
    `update member set
       display_name = coalesce($3, display_name),
       role         = coalesce($4, role),
       color        = coalesce($5, color),
       active       = coalesce($6, active)
     where household_id = $1 and id = $2
     returning *`,
    [householdId, memberId, patch.displayName ?? null, patch.role ?? null, patch.color ?? null,
     patch.active ?? null],
  );
  if (rows.length === 0) return null;
  const member = toMember(rows[0]!);
  await indexDocument(tx, {
    entity: 'member', id: member.id, householdId, title: member.displayName, body: member.role,
  });
  return member;
}

/**
 * How many active owners a household has.
 *
 * The one household-integrity rule this layer does enforce, because it is a
 * data invariant rather than a permission: a household with no owner cannot be
 * administered by anybody, ever, and no amount of correct permission checking
 * recovers from it.
 */
export async function countActiveOwners(tx: Queryable, householdId: UUID): Promise<number> {
  const { rows } = await tx.query<{ n: number }>(
    `select count(*)::int as n from member where household_id = $1 and role = 'owner' and active`,
    [householdId],
  );
  return Number(rows[0]?.n ?? 0);
}

/* ------------------------------------------------------------ invitations */

/**
 * An invitation, minus its secret.
 *
 * `token_hash` is never selected. A screen that lists pending invitations has
 * no use for it, and a hash that never leaves this file cannot be leaked by a
 * response body somebody forgot to trim.
 */
export interface InvitationSummary {
  id: UUID;
  householdId: UUID;
  role: Role;
  email: string | null;
  createdBy: UUID;
  createdAt: string;
  expiresAt: string;
  acceptedAt: string | null;
}

interface InvitationRow {
  id: string; household_id: string; role: string; email: string | null;
  created_by: string; created_at: string; expires_at: string; accepted_at: string | null;
}

const toInvitation = (r: InvitationRow): InvitationSummary => ({
  id: r.id, householdId: r.household_id, role: r.role as Role, email: r.email,
  createdBy: r.created_by, createdAt: new Date(r.created_at).toISOString(),
  expiresAt: new Date(r.expires_at).toISOString(),
  acceptedAt: r.accepted_at === null ? null : new Date(r.accepted_at).toISOString(),
});

/**
 * Invitations for a household, newest first.
 *
 * `pending` filters to the ones that are still a way in — unaccepted and
 * unexpired — which is the only set anybody can act on. Expiry is compared
 * against a caller-supplied instant rather than `now()` so the answer matches
 * the rest of the request; the API tier reads the clock once and threads it.
 */
export async function listInvitations(
  tx: Queryable, householdId: UUID, options: { pending?: boolean; now?: string } = {},
): Promise<InvitationSummary[]> {
  const { rows } = await tx.query<InvitationRow>(
    `select id, household_id, role, email, created_by, created_at, expires_at, accepted_at
       from invitation
      where household_id = $1
        and ($2::boolean is not true or (accepted_at is null and expires_at > $3::timestamptz))
      order by created_at desc, id asc`,
    [householdId, options.pending ?? false, options.now ?? new Date(0).toISOString()],
  );
  return rows.map(toInvitation);
}

export async function getInvitation(
  tx: Queryable, householdId: UUID, invitationId: UUID,
): Promise<InvitationSummary | null> {
  const { rows } = await tx.query<InvitationRow>(
    `select id, household_id, role, email, created_by, created_at, expires_at, accepted_at
       from invitation where household_id = $1 and id = $2`,
    [householdId, invitationId],
  );
  return rows.length > 0 ? toInvitation(rows[0]!) : null;
}

/**
 * Revoke an unaccepted invitation by deleting the row.
 *
 * A hard delete, and deliberately: the row IS the credential — while it exists,
 * whoever holds the matching token can still walk into the household. Marking
 * it "revoked" and leaving it would keep a live hash in the table, and the
 * accepted ones are the only invitations with any history worth keeping. The
 * `accepted_at is null` clause is what makes that distinction unforgettable:
 * how somebody actually joined can never be erased through this path.
 */
export async function deleteInvitation(
  tx: Queryable, householdId: UUID, invitationId: UUID,
): Promise<boolean> {
  const { rowCount } = await tx.query(
    `delete from invitation where household_id = $1 and id = $2 and accepted_at is null`,
    [householdId, invitationId],
  );
  return rowCount > 0;
}

/* -------------------------------------------------------------- schedules */

export async function listSchedules(tx: Queryable, householdId: UUID): Promise<Schedule[]> {
  const { rows } = await tx.query<ScheduleRow>(
    `select * from schedule where household_id = $1 and not archived order by name asc`,
    [householdId],
  );
  return rows.map(toSchedule);
}

/**
 * The schedule a domain's events live on, creating it on first use.
 *
 * Mini-apps are views over one engine (PRODUCT_SPEC §2), so "the Practice
 * schedule" is a lookup rather than something the user has to set up before
 * they can add their first practice.
 */
export async function ensureSchedule(
  tx: Queryable,
  householdId: UUID,
  domain: DomainKey,
  name: string,
): Promise<Schedule> {
  const existing = await tx.query<ScheduleRow>(
    `select * from schedule where household_id = $1 and domain = $2 and not archived
      order by name asc, id asc limit 1`,
    [householdId, domain],
  );
  if (existing.rows.length > 0) return toSchedule(existing.rows[0]!);

  const { rows } = await tx.query<ScheduleRow>(
    `insert into schedule (household_id, domain, name) values ($1,$2,$3) returning *`,
    [householdId, domain, name],
  );
  return toSchedule(rows[0]!);
}

/* ----------------------------------------------------------------- events */

const EVENT_SELECT = `
  select e.*, coalesce(
    (select array_agg(x.exception_date order by x.exception_date)
       from event_exception x where x.event_id = e.id), '{}') as exceptions
    from event e`;

export async function getEvent(tx: Queryable, householdId: UUID, eventId: UUID): Promise<EventRecord | null> {
  const { rows } = await tx.query<EventRow>(
    `${EVENT_SELECT} where e.household_id = $1 and e.id = $2`,
    [householdId, eventId],
  );
  return rows.length > 0 ? toEvent(rows[0]!) : null;
}

/**
 * Every base event that could possibly produce an occurrence in a window.
 *
 * A recurring series starts before the window and may run into it, so the
 * filter cannot simply be `starts_at between from and to` — a weekly practice
 * created in September is invisible in December under that predicate. Instead:
 * anything that starts before the window ends, and either recurs (the engine
 * decides where it lands) or ends after the window starts.
 *
 * Overrides come back too; the recurrence engine needs them to materialise a
 * moved occurrence.
 */
export async function listEventsForWindow(
  tx: Queryable,
  householdId: UUID,
  window: { from: string; to: string },
  options: { domains?: readonly DomainKey[] } = {},
): Promise<EventRecord[]> {
  const { rows } = await tx.query<EventRow>(
    `${EVENT_SELECT}
      where e.household_id = $1
        and e.starts_at < $3
        and (e.rrule_freq is not null or e.ends_at > $2)
        and ($4::text[] is null or e.domain = any($4::text[]))
      order by e.starts_at asc, e.id asc`,
    [householdId, window.from, window.to, (options.domains as string[] | undefined) ?? null],
  );
  return rows.map(toEvent);
}

export interface CreateEventInput {
  householdId: UUID;
  scheduleId: UUID;
  domain: DomainKey;
  title: string;
  notes?: string;
  location?: string;
  startsAt: string;
  endsAt: string;
  allDay?: boolean;
  timezone: string;
  status?: EventRecord['status'];
  createdBy: UUID;
  recurrence?: RecurrenceRule;
  participants?: ReadonlyArray<{ memberId: UUID; role?: 'attendee' | 'responsible' | 'optional' }>;
  seriesId?: UUID;
  recurrenceId?: string;
}

export async function createEvent(tx: Queryable, input: CreateEventInput): Promise<EventRecord> {
  const r = input.recurrence;
  const { rows } = await tx.query<EventRow>(
    `insert into event (
       household_id, schedule_id, domain, title, notes, location, starts_at, ends_at,
       all_day, timezone, status, created_by,
       rrule_freq, rrule_interval, rrule_by_weekday, rrule_by_monthday,
       rrule_until, rrule_count, rrule_week_start, series_id, recurrence_id)
     values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,coalesce($11,'confirmed'),$12,
             $13,$14,$15,$16,$17,$18,$19,$20,$21)
     returning *`,
    [
      input.householdId, input.scheduleId, input.domain, input.title.trim(),
      input.notes ?? null, input.location ?? null, input.startsAt, input.endsAt,
      input.allDay ?? false, input.timezone, input.status ?? null, input.createdBy,
      r?.freq ?? null, r?.interval ?? null, r?.byWeekday ?? null, r?.byMonthDay ?? null,
      r?.until ?? null, r?.count ?? null, r?.weekStart ?? null,
      input.seriesId ?? null, input.recurrenceId ?? null,
    ],
  );
  const row = rows[0]!;

  for (const date of r?.exceptions ?? []) {
    await tx.query(
      `insert into event_exception (event_id, exception_date) values ($1,$2) on conflict do nothing`,
      [row.id, date],
    );
  }

  const participants = input.participants ?? [];
  for (const p of participants) {
    await tx.query(
      `insert into event_participant (event_id, member_id, role) values ($1,$2,coalesce($3,'attendee'))
       on conflict (event_id, member_id) do update set role = excluded.role`,
      [row.id, p.memberId, p.role ?? null],
    );
  }

  const event = await getEvent(tx, input.householdId, row.id);
  await indexDocument(tx, {
    entity: 'event',
    id: row.id,
    householdId: input.householdId,
    title: input.title.trim(),
    ...(input.notes || input.location
      ? { body: [input.location, input.notes].filter(Boolean).join(' — ') }
      : {}),
    domain: input.domain,
    at: input.startsAt,
    ...(participants.length > 0 ? { memberIds: participants.map((p) => p.memberId) } : {}),
  });
  return event!;
}

export async function updateEvent(
  tx: Queryable,
  householdId: UUID,
  eventId: UUID,
  patch: Partial<Omit<CreateEventInput, 'householdId' | 'createdBy'>>,
): Promise<EventRecord | null> {
  const r = patch.recurrence;
  const { rows } = await tx.query<EventRow>(
    `update event set
       schedule_id = coalesce($3, schedule_id),
       domain      = coalesce($4, domain),
       title       = coalesce($5, title),
       notes       = coalesce($6, notes),
       location    = coalesce($7, location),
       starts_at   = coalesce($8, starts_at),
       ends_at     = coalesce($9, ends_at),
       all_day     = coalesce($10, all_day),
       timezone    = coalesce($11, timezone),
       status      = coalesce($12, status),
       rrule_freq        = coalesce($13, rrule_freq),
       rrule_interval    = coalesce($14, rrule_interval),
       rrule_by_weekday  = coalesce($15, rrule_by_weekday),
       rrule_by_monthday = coalesce($16, rrule_by_monthday),
       rrule_until       = coalesce($17, rrule_until),
       rrule_count       = coalesce($18, rrule_count),
       rrule_week_start  = coalesce($19, rrule_week_start),
       updated_at        = now()
     where household_id = $1 and id = $2
     returning *`,
    [
      householdId, eventId, patch.scheduleId ?? null, patch.domain ?? null,
      patch.title?.trim() ?? null, patch.notes ?? null, patch.location ?? null,
      patch.startsAt ?? null, patch.endsAt ?? null, patch.allDay ?? null,
      patch.timezone ?? null, patch.status ?? null,
      r?.freq ?? null, r?.interval ?? null, r?.byWeekday ?? null, r?.byMonthDay ?? null,
      r?.until ?? null, r?.count ?? null, r?.weekStart ?? null,
    ],
  );
  if (rows.length === 0) return null;

  if (patch.participants !== undefined) {
    await tx.query(`delete from event_participant where event_id = $1`, [eventId]);
    for (const p of patch.participants) {
      await tx.query(
        `insert into event_participant (event_id, member_id, role) values ($1,$2,coalesce($3,'attendee'))`,
        [eventId, p.memberId, p.role ?? null],
      );
    }
  }

  const event = await getEvent(tx, householdId, eventId);
  if (event !== null) {
    await indexDocument(tx, {
      entity: 'event', id: eventId, householdId, title: event.title,
      ...(event.location || event.notes
        ? { body: [event.location, event.notes].filter(Boolean).join(' — ') }
        : {}),
      domain: event.domain, at: event.startsAt,
    });
  }
  return event;
}

/**
 * Cancel an event, or one occurrence of a series.
 *
 * Cancelling is a status change, never a DELETE: a cancelled practice that
 * vanishes without trace is indistinguishable from one that never existed, and
 * the family wants to know it was called off.
 */
export async function cancelEvent(
  tx: Queryable,
  householdId: UUID,
  eventId: UUID,
  scope: 'occurrence' | 'series',
  occurrenceStart?: string,
): Promise<boolean> {
  if (scope === 'series' || occurrenceStart === undefined) {
    const { rowCount } = await tx.query(
      `update event set status = 'cancelled', updated_at = now() where household_id = $1 and id = $2`,
      [householdId, eventId],
    );
    if (rowCount > 0) await unindexDocument(tx, 'event', eventId);
    return rowCount > 0;
  }

  // One occurrence: an EXDATE on the series, keyed by the occurrence's local
  // date, which is what the recurrence engine matches exceptions on.
  const event = await getEvent(tx, householdId, eventId);
  if (event === null) return false;
  const localDate = new Intl.DateTimeFormat('en-CA', {
    timeZone: event.timezone, year: 'numeric', month: '2-digit', day: '2-digit',
  }).format(new Date(occurrenceStart));
  await tx.query(
    `insert into event_exception (event_id, exception_date) values ($1,$2) on conflict do nothing`,
    [eventId, localDate],
  );
  return true;
}

export async function listParticipants(
  tx: Queryable,
  householdId: UUID,
  eventIds: readonly UUID[],
): Promise<Array<{ eventId: UUID; memberId: UUID; role: 'attendee' | 'responsible' | 'optional' }>> {
  if (eventIds.length === 0) return [];
  const { rows } = await tx.query<{ event_id: string; member_id: string; role: string }>(
    `select p.event_id, p.member_id, p.role
       from event_participant p
       join event e on e.id = p.event_id
      where e.household_id = $1 and p.event_id = any($2::uuid[])`,
    [householdId, eventIds as string[]],
  );
  return rows.map((r) => ({
    eventId: r.event_id,
    memberId: r.member_id,
    role: r.role as 'attendee' | 'responsible' | 'optional',
  }));
}

/* -------------------------------------------------------------- reminders */

export async function listReminders(
  tx: Queryable,
  householdId: UUID,
  options: { status?: readonly string[] } = {},
): Promise<Reminder[]> {
  const { rows } = await tx.query<ReminderRow>(
    `select * from reminder
      where household_id = $1
        and ($2::text[] is null or status = any($2::text[]))
      order by due_at asc, id asc`,
    [householdId, (options.status as string[] | undefined) ?? null],
  );
  return rows.map(toReminder);
}

export async function getReminder(tx: Queryable, householdId: UUID, id: UUID): Promise<Reminder | null> {
  const { rows } = await tx.query<ReminderRow>(
    `select * from reminder where household_id = $1 and id = $2`, [householdId, id],
  );
  return rows.length > 0 ? toReminder(rows[0]!) : null;
}

export async function insertReminder(tx: Queryable, reminder: Omit<Reminder, 'id'> & { id?: UUID }): Promise<Reminder> {
  const r = reminder.recurrence;
  const { rows } = await tx.query<ReminderRow>(
    `insert into reminder (household_id, event_id, title, due_at, assigned_to, status,
                           snoozed_until, completed_at, rrule_freq, rrule_interval, rrule_until)
     values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,
    [
      reminder.householdId, reminder.eventId ?? null, reminder.title, reminder.dueAt,
      reminder.assignedTo ?? null, reminder.status, reminder.snoozedUntil ?? null,
      reminder.completedAt ?? null, r?.freq ?? null, r?.interval ?? null, r?.until ?? null,
    ],
  );
  const saved = toReminder(rows[0]!);
  await indexDocument(tx, {
    entity: 'reminder', id: saved.id, householdId: saved.householdId,
    title: saved.title, at: saved.dueAt,
    ...(saved.assignedTo ? { memberIds: [saved.assignedTo] } : {}),
  });
  return saved;
}

/** Persist a reminder the domain module has already transitioned. */
export async function saveReminder(tx: Queryable, reminder: Reminder): Promise<Reminder | null> {
  const r = reminder.recurrence;
  const { rows } = await tx.query<ReminderRow>(
    `update reminder set
       title = $3, due_at = $4, assigned_to = $5, status = $6,
       snoozed_until = $7, completed_at = $8,
       rrule_freq = $9, rrule_interval = $10, rrule_until = $11
     where household_id = $1 and id = $2 returning *`,
    [
      reminder.householdId, reminder.id, reminder.title, reminder.dueAt,
      reminder.assignedTo ?? null, reminder.status, reminder.snoozedUntil ?? null,
      reminder.completedAt ?? null, r?.freq ?? null, r?.interval ?? null, r?.until ?? null,
    ],
  );
  if (rows.length === 0) return null;
  const saved = toReminder(rows[0]!);
  if (saved.status === 'completed' || saved.status === 'dismissed') {
    await unindexDocument(tx, 'reminder', saved.id);
  } else {
    await indexDocument(tx, {
      entity: 'reminder', id: saved.id, householdId: saved.householdId,
      title: saved.title, at: saved.dueAt,
      ...(saved.assignedTo ? { memberIds: [saved.assignedTo] } : {}),
    });
  }
  return saved;
}

/**
 * Delete a reminder outright.
 *
 * Nothing in the schema points at a reminder — no foreign key, no ledger line,
 * no audit row that would be orphaned — so there is no history here to protect
 * and nothing to gain from a tombstone. `completed` and `dismissed` already
 * exist for the reminders that ran their course; this path is for the ones that
 * should never have been typed, and it leaves nothing behind, including in the
 * search index.
 */
export async function deleteReminder(tx: Queryable, householdId: UUID, id: UUID): Promise<boolean> {
  const { rowCount } = await tx.query(
    `delete from reminder where household_id = $1 and id = $2`, [householdId, id],
  );
  if (rowCount > 0) await unindexDocument(tx, 'reminder', id);
  return rowCount > 0;
}

/* ------------------------------------------------------- personal lists */

export async function listShoppingItems(
  tx: Queryable, householdId: UUID, options: { status?: readonly string[] } = {},
): Promise<ShoppingItem[]> {
  const { rows } = await tx.query<ShoppingItemRow>(
    `select * from shopping_item
      where household_id = $1 and ($2::text[] is null or status = any($2::text[]))
      order by name asc, id asc`,
    [householdId, (options.status as string[] | undefined) ?? null],
  );
  return rows.map(toShoppingItem);
}

export async function getShoppingItem(tx: Queryable, householdId: UUID, id: UUID): Promise<ShoppingItem | null> {
  const { rows } = await tx.query<ShoppingItemRow>(
    `select * from shopping_item where household_id = $1 and id = $2`, [householdId, id],
  );
  return rows.length > 0 ? toShoppingItem(rows[0]!) : null;
}

export async function insertShoppingItem(tx: Queryable, item: Omit<ShoppingItem, 'id'>): Promise<ShoppingItem> {
  const { rows } = await tx.query<ShoppingItemRow>(
    `insert into shopping_item (household_id, list_name, name, quantity, status, category, store)
     values ($1,$2,$3,$4,$5,$6,$7) returning *`,
    [item.householdId, item.listName, item.name, item.quantity, item.status,
     item.category ?? null, item.store ?? null],
  );
  const saved = toShoppingItem(rows[0]!);
  await indexDocument(tx, {
    entity: 'shopping_item', id: saved.id, householdId: saved.householdId,
    title: saved.name, ...(saved.store ? { body: saved.store } : {}), domain: 'shopping',
  });
  return saved;
}

export async function saveShoppingItem(tx: Queryable, item: ShoppingItem): Promise<ShoppingItem | null> {
  const { rows } = await tx.query<ShoppingItemRow>(
    `update shopping_item set list_name=$3, name=$4, quantity=$5, status=$6, category=$7, store=$8
      where household_id=$1 and id=$2 returning *`,
    [item.householdId, item.id, item.listName, item.name, item.quantity, item.status,
     item.category ?? null, item.store ?? null],
  );
  if (rows.length === 0) return null;
  const saved = toShoppingItem(rows[0]!);
  if (saved.status === 'removed') await unindexDocument(tx, 'shopping_item', saved.id);
  else await indexDocument(tx, {
    entity: 'shopping_item', id: saved.id, householdId: saved.householdId,
    title: saved.name, ...(saved.store ? { body: saved.store } : {}), domain: 'shopping',
  });
  return saved;
}

export async function listErrands(
  tx: Queryable, householdId: UUID, options: { status?: readonly string[] } = {},
): Promise<Errand[]> {
  const { rows } = await tx.query<ErrandRow>(
    `select * from errand
      where household_id = $1 and ($2::text[] is null or status = any($2::text[]))
      order by due_at asc nulls last, id asc`,
    [householdId, (options.status as string[] | undefined) ?? null],
  );
  return rows.map(toErrand);
}

export async function getErrand(tx: Queryable, householdId: UUID, id: UUID): Promise<Errand | null> {
  const { rows } = await tx.query<ErrandRow>(
    `select * from errand where household_id = $1 and id = $2`, [householdId, id],
  );
  return rows.length > 0 ? toErrand(rows[0]!) : null;
}

export async function insertErrand(tx: Queryable, errand: Omit<Errand, 'id'>): Promise<Errand> {
  const { rows } = await tx.query<ErrandRow>(
    `insert into errand (household_id, title, assigned_to, due_at, location, status)
     values ($1,$2,$3,$4,$5,$6) returning *`,
    [errand.householdId, errand.title, errand.assignedTo ?? null, errand.dueAt ?? null,
     errand.location ?? null, errand.status],
  );
  const saved = toErrand(rows[0]!);
  await indexDocument(tx, {
    entity: 'errand', id: saved.id, householdId: saved.householdId, title: saved.title,
    ...(saved.location ? { body: saved.location } : {}), domain: 'errands',
    ...(saved.dueAt ? { at: saved.dueAt } : {}),
    ...(saved.assignedTo ? { memberIds: [saved.assignedTo] } : {}),
  });
  return saved;
}

export async function saveErrand(tx: Queryable, errand: Errand): Promise<Errand | null> {
  const { rows } = await tx.query<ErrandRow>(
    `update errand set title=$3, assigned_to=$4, due_at=$5, location=$6, status=$7
      where household_id=$1 and id=$2 returning *`,
    [errand.householdId, errand.id, errand.title, errand.assignedTo ?? null,
     errand.dueAt ?? null, errand.location ?? null, errand.status],
  );
  if (rows.length === 0) return null;
  const saved = toErrand(rows[0]!);
  if (saved.status === 'done' || saved.status === 'cancelled') {
    await unindexDocument(tx, 'errand', saved.id);
  } else {
    await indexDocument(tx, {
      entity: 'errand', id: saved.id, householdId: saved.householdId, title: saved.title,
      ...(saved.location ? { body: saved.location } : {}), domain: 'errands',
      ...(saved.dueAt ? { at: saved.dueAt } : {}),
    });
  }
  return saved;
}

/**
 * Delete a shopping item, and an errand, outright.
 *
 * Same reasoning as `deleteReminder`: both tables are leaves. `removed` and
 * `cancelled` remain the right answer for "we decided not to buy it" — they
 * keep the decision visible — while these are for the row that was a mistake.
 * Keeping a mistake forever is its own kind of dishonesty about the list.
 */
export async function deleteShoppingItem(tx: Queryable, householdId: UUID, id: UUID): Promise<boolean> {
  const { rowCount } = await tx.query(
    `delete from shopping_item where household_id = $1 and id = $2`, [householdId, id],
  );
  if (rowCount > 0) await unindexDocument(tx, 'shopping_item', id);
  return rowCount > 0;
}

export async function deleteErrand(tx: Queryable, householdId: UUID, id: UUID): Promise<boolean> {
  const { rowCount } = await tx.query(
    `delete from errand where household_id = $1 and id = $2`, [householdId, id],
  );
  if (rowCount > 0) await unindexDocument(tx, 'errand', id);
  return rowCount > 0;
}

/* ----------------------------------------------------------------- inbox */

export async function listInboxItems(
  tx: Queryable, householdId: UUID, options: { status?: readonly string[] } = {},
): Promise<InboxItem[]> {
  const { rows } = await tx.query<InboxItemRow>(
    `select * from inbox_item
      where household_id = $1 and ($2::text[] is null or status = any($2::text[]))
      order by captured_at desc, id asc`,
    [householdId, (options.status as string[] | undefined) ?? null],
  );
  return rows.map(toInboxItem);
}

export async function getInboxItem(tx: Queryable, householdId: UUID, id: UUID): Promise<InboxItem | null> {
  const { rows } = await tx.query<InboxItemRow>(
    `select * from inbox_item where household_id = $1 and id = $2`, [householdId, id],
  );
  return rows.length > 0 ? toInboxItem(rows[0]!) : null;
}

export async function insertInboxItem(
  tx: Queryable,
  input: { householdId: UUID; rawText: string; capturedBy: UUID },
): Promise<InboxItem> {
  const { rows } = await tx.query<InboxItemRow>(
    `insert into inbox_item (household_id, raw_text, captured_by) values ($1,$2,$3) returning *`,
    [input.householdId, input.rawText.trim(), input.capturedBy],
  );
  const saved = toInboxItem(rows[0]!);
  await indexDocument(tx, {
    entity: 'inbox_item', id: saved.id, householdId: saved.householdId,
    title: saved.rawText.slice(0, 120), domain: 'inbox', at: saved.capturedAt,
  });
  return saved;
}

/** Record what the classifier proposed, without acting on it. */
export async function classifyInboxItemRow(
  tx: Queryable,
  householdId: UUID,
  id: UUID,
  suggestedDomain: DomainKey,
  proposal: unknown,
): Promise<InboxItem | null> {
  const { rows } = await tx.query<InboxItemRow>(
    `update inbox_item set suggested_domain = $3, proposal = $4, status = 'classified'
      where household_id = $1 and id = $2 returning *`,
    [householdId, id, suggestedDomain, JSON.stringify(proposal)],
  );
  return rows.length > 0 ? toInboxItem(rows[0]!) : null;
}

export async function resolveInboxItem(
  tx: Queryable,
  householdId: UUID,
  id: UUID,
  status: 'converted' | 'dismissed',
  converted?: { entity: string; id: UUID },
): Promise<InboxItem | null> {
  const { rows } = await tx.query<InboxItemRow>(
    `update inbox_item set status = $3, converted_to = $4, converted_id = $5
      where household_id = $1 and id = $2 returning *`,
    [householdId, id, status, converted?.entity ?? null, converted?.id ?? null],
  );
  if (rows.length === 0) return null;
  await unindexDocument(tx, 'inbox_item', id);
  return toInboxItem(rows[0]!);
}

/* --------------------------------------------------------------- business */

export async function getBusinessForHousehold(tx: Queryable, householdId: UUID): Promise<Business | null> {
  const { rows } = await tx.query<BusinessRow>(
    `select * from business where household_id = $1 order by created_at asc limit 1`, [householdId],
  );
  return rows.length > 0 ? toBusiness(rows[0]!) : null;
}

export async function createBusiness(
  tx: Queryable,
  input: { householdId: UUID; name: string; timezone: string; taxSetAsideRate?: number },
): Promise<Business> {
  const { rows } = await tx.query<BusinessRow>(
    // `coalesce($4, 0)` would let Postgres infer INTEGER from the literal and
    // then refuse a rate like 0.0825. The cast pins it to the column's type.
    `insert into business (household_id, name, timezone, tax_set_aside_rate)
     values ($1,$2,$3,coalesce($4::numeric,0)) returning *`,
    [input.householdId, input.name, input.timezone, input.taxSetAsideRate ?? null],
  );
  return toBusiness(rows[0]!);
}

export async function updateBusiness(
  tx: Queryable, householdId: UUID, businessId: UUID,
  patch: { name?: string; timezone?: string; taxSetAsideRate?: number },
): Promise<Business | null> {
  const { rows } = await tx.query<BusinessRow>(
    `update business set name = coalesce($3,name), timezone = coalesce($4,timezone),
                         tax_set_aside_rate = coalesce($5::numeric,tax_set_aside_rate)
      where household_id = $1 and id = $2 returning *`,
    [householdId, businessId, patch.name ?? null, patch.timezone ?? null, patch.taxSetAsideRate ?? null],
  );
  return rows.length > 0 ? toBusiness(rows[0]!) : null;
}

/**
 * Business reads take the household too, even though `business_id` alone would
 * find the row. That is the point: it makes a cross-tenant read impossible to
 * write by accident, which CR-009 is exactly about.
 */
async function assertBusinessInHousehold(tx: Queryable, householdId: UUID, businessId: UUID): Promise<boolean> {
  const { rows } = await tx.query<{ id: string }>(
    `select id from business where id = $1 and household_id = $2`, [businessId, householdId],
  );
  return rows.length > 0;
}

export async function listEmployees(tx: Queryable, householdId: UUID, businessId: UUID): Promise<Employee[]> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return [];
  const { rows } = await tx.query<EmployeeRow>(
    `select * from employee where business_id = $1 order by active desc, display_name asc`, [businessId],
  );
  return rows.map(toEmployee);
}

export async function insertEmployee(
  tx: Queryable, householdId: UUID,
  input: { businessId: UUID; displayName: string; hourlyRateCents?: number; memberId?: UUID | null },
): Promise<Employee | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, input.businessId))) return null;
  const { rows } = await tx.query<EmployeeRow>(
    `insert into employee (business_id, member_id, display_name, hourly_rate_cents)
     values ($1,$2,$3,coalesce($4,0)) returning *`,
    [input.businessId, input.memberId ?? null, input.displayName.trim(), input.hourlyRateCents ?? null],
  );
  const saved = toEmployee(rows[0]!);
  await indexDocument(tx, {
    entity: 'employee', id: saved.id, householdId, title: saved.displayName, businessId: input.businessId,
  });
  return saved;
}

export async function saveEmployee(
  tx: Queryable, householdId: UUID, employee: Employee,
): Promise<Employee | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, employee.businessId))) return null;
  const { rows } = await tx.query<EmployeeRow>(
    `update employee set display_name=$3, hourly_rate_cents=$4, active=$5, member_id=$6
      where business_id=$1 and id=$2 returning *`,
    [employee.businessId, employee.id, employee.displayName, employee.hourlyRate,
     employee.active, employee.memberId],
  );
  if (rows.length === 0) return null;
  const saved = toEmployee(rows[0]!);
  await indexDocument(tx, {
    entity: 'employee', id: saved.id, householdId, title: saved.displayName, businessId: saved.businessId,
  });
  return saved;
}

/**
 * Has this employee any history the business would lose by deleting the row?
 *
 * Shifts are the ledger of who worked, and `shift.employee_id` is
 * `on delete set null` — deleting the employee would leave those hours
 * attributed to nobody, which reads as "an unassigned shift" rather than "the
 * person who worked it is gone". Swaps carry the same record. Availability and
 * time-off are the employee's own declarations about the future and cascade
 * away without costing anyone anything, so they deliberately do NOT count.
 */
export async function employeeHasHistory(
  tx: Queryable, householdId: UUID, businessId: UUID, employeeId: UUID,
): Promise<boolean> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return false;
  const { rows } = await tx.query<{ n: number }>(
    `select (
       (select count(*) from shift where business_id = $1 and employee_id = $2) +
       (select count(*) from shift_swap
         where business_id = $1 and (from_employee_id = $2 or to_employee_id = $2))
     )::int as n`,
    [businessId, employeeId],
  );
  return Number(rows[0]?.n ?? 0) > 0;
}

/**
 * Retire an employee who HAS worked: keep the row, stop the scheduling.
 *
 * `assignShift` already refuses an inactive employee and `analyzeSchedule`
 * already reads `active`, so this is the whole of the behaviour change — the
 * coverage rules were not touched to make removal work. The search document
 * goes, because a person nobody can be scheduled onto has no business turning
 * up when you search for somebody to schedule.
 */
export async function deactivateEmployee(
  tx: Queryable, householdId: UUID, businessId: UUID, employeeId: UUID,
): Promise<Employee | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return null;
  const { rows } = await tx.query<EmployeeRow>(
    `update employee set active = false where business_id = $1 and id = $2 returning *`,
    [businessId, employeeId],
  );
  if (rows.length === 0) return null;
  await unindexDocument(tx, 'employee', employeeId);
  return toEmployee(rows[0]!);
}

/**
 * Delete an employee who never worked.
 *
 * Only ever called once `employeeHasHistory` has said no, so the cascade this
 * fires reaches nothing but that employee's own availability windows and
 * time-off requests. This is the path the reported bug actually needed: a test
 * employee typed in to see what the screen does should be able to leave without
 * a trace.
 */
export async function deleteEmployee(
  tx: Queryable, householdId: UUID, businessId: UUID, employeeId: UUID,
): Promise<boolean> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return false;
  const { rowCount } = await tx.query(
    `delete from employee where business_id = $1 and id = $2`, [businessId, employeeId],
  );
  if (rowCount > 0) await unindexDocument(tx, 'employee', employeeId);
  return rowCount > 0;
}

export async function listShifts(
  tx: Queryable, householdId: UUID, businessId: UUID, window: { from: string; to: string },
): Promise<Shift[]> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return [];
  const { rows } = await tx.query<ShiftRow>(
    `select * from shift where business_id = $1 and starts_at < $3 and ends_at > $2
      order by starts_at asc, id asc`,
    [businessId, window.from, window.to],
  );
  return rows.map(toShift);
}

export async function insertShift(
  tx: Queryable, householdId: UUID,
  input: { businessId: UUID; employeeId?: UUID | null; startsAt: string; endsAt: string; role?: string },
): Promise<Shift | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, input.businessId))) return null;
  const { rows } = await tx.query<ShiftRow>(
    `insert into shift (business_id, employee_id, starts_at, ends_at, role)
     values ($1,$2,$3,$4,$5) returning *`,
    [input.businessId, input.employeeId ?? null, input.startsAt, input.endsAt, input.role ?? null],
  );
  return toShift(rows[0]!);
}

export async function saveShift(tx: Queryable, householdId: UUID, shift: Shift): Promise<Shift | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, shift.businessId))) return null;
  const { rows } = await tx.query<ShiftRow>(
    `update shift set employee_id=$3, starts_at=$4, ends_at=$5, status=$6, role=$7
      where business_id=$1 and id=$2 returning *`,
    [shift.businessId, shift.id, shift.employeeId, shift.startsAt, shift.endsAt,
     shift.status, shift.role ?? null],
  );
  return rows.length > 0 ? toShift(rows[0]!) : null;
}

/**
 * One shift, scoped to the household's own business.
 *
 * `listShifts` needs a window, and "the shift the user just tapped" has no
 * window — asking for one would mean guessing a range wide enough to contain
 * the answer, which is how a delete quietly starts 404ing on old rows.
 */
export async function getShift(
  tx: Queryable, householdId: UUID, businessId: UUID, shiftId: UUID,
): Promise<Shift | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return null;
  const { rows } = await tx.query<ShiftRow>(
    `select * from shift where business_id = $1 and id = $2`, [businessId, shiftId],
  );
  return rows.length > 0 ? toShift(rows[0]!) : null;
}

/**
 * Delete a shift that was never published.
 *
 * A draft is a plan nobody was told about, so removing it removes nothing an
 * employee ever saw. A published shift is a promise that was made, and the API
 * cancels those instead — `cancelled` is already INERT to the staffing engine,
 * so the coverage the shift was filling reopens either way while the record of
 * having promised it survives.
 */
export async function deleteShift(
  tx: Queryable, householdId: UUID, businessId: UUID, shiftId: UUID,
): Promise<boolean> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return false;
  // `shift_swap.shift_id` cascades, so a shift somebody has asked to swap is
  // left alone here and cancelled instead — losing the request would look, to
  // the employee who made it, exactly like being ignored.
  const { rowCount } = await tx.query(
    `delete from shift
      where business_id = $1 and id = $2 and status = 'draft'
        and not exists (select 1 from shift_swap where shift_id = $2)`,
    [businessId, shiftId],
  );
  return rowCount > 0;
}

export async function listAvailability(
  tx: Queryable, householdId: UUID, businessId: UUID,
): Promise<Availability[]> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return [];
  const { rows } = await tx.query<AvailabilityRow>(
    `select * from availability where business_id = $1 order by employee_id, weekday, start_minute`,
    [businessId],
  );
  return rows.map(toAvailability);
}

export async function insertAvailability(
  tx: Queryable, householdId: UUID, a: Omit<Availability, 'id'>,
): Promise<Availability | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, a.businessId))) return null;
  const { rows } = await tx.query<AvailabilityRow>(
    `insert into availability (business_id, employee_id, weekday, start_minute, end_minute, available, preferred_weekly_hours)
     values ($1,$2,$3,$4,$5,$6,$7) returning *`,
    [a.businessId, a.employeeId, a.weekday, a.startMinute, a.endMinute, a.available,
     a.preferredWeeklyHours ?? null],
  );
  return toAvailability(rows[0]!);
}

export async function listTimeOff(
  tx: Queryable, householdId: UUID, businessId: UUID,
): Promise<TimeOffRequest[]> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return [];
  const { rows } = await tx.query<TimeOffRow>(
    `select * from time_off_request where business_id = $1 order by starts_at desc`, [businessId],
  );
  return rows.map(toTimeOff);
}

export async function insertTimeOff(
  tx: Queryable, householdId: UUID,
  input: { businessId: UUID; employeeId: UUID; startsAt: string; endsAt: string; reason?: string },
): Promise<TimeOffRequest | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, input.businessId))) return null;
  const { rows } = await tx.query<TimeOffRow>(
    `insert into time_off_request (business_id, employee_id, starts_at, ends_at, reason)
     values ($1,$2,$3,$4,$5) returning *`,
    [input.businessId, input.employeeId, input.startsAt, input.endsAt, input.reason ?? null],
  );
  return toTimeOff(rows[0]!);
}

export async function saveTimeOff(
  tx: Queryable, householdId: UUID, request: TimeOffRequest,
): Promise<TimeOffRequest | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, request.businessId))) return null;
  const { rows } = await tx.query<TimeOffRow>(
    `update time_off_request set status=$3, reviewed_by=$4 where business_id=$1 and id=$2 returning *`,
    [request.businessId, request.id, request.status, request.reviewedBy ?? null],
  );
  return rows.length > 0 ? toTimeOff(rows[0]!) : null;
}

export async function listSwaps(tx: Queryable, householdId: UUID, businessId: UUID): Promise<ShiftSwap[]> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return [];
  const { rows } = await tx.query<ShiftSwapRow>(
    `select * from shift_swap where business_id = $1 order by status asc, id asc`, [businessId],
  );
  return rows.map(toShiftSwap);
}

export async function insertSwap(
  tx: Queryable, householdId: UUID,
  input: { businessId: UUID; shiftId: UUID; fromEmployeeId: UUID },
): Promise<ShiftSwap | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, input.businessId))) return null;
  const { rows } = await tx.query<ShiftSwapRow>(
    `insert into shift_swap (business_id, shift_id, from_employee_id) values ($1,$2,$3) returning *`,
    [input.businessId, input.shiftId, input.fromEmployeeId],
  );
  return toShiftSwap(rows[0]!);
}

export async function saveSwap(tx: Queryable, householdId: UUID, swap: ShiftSwap): Promise<ShiftSwap | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, swap.businessId))) return null;
  const { rows } = await tx.query<ShiftSwapRow>(
    `update shift_swap set to_employee_id=$3, status=$4, reviewed_by=$5
      where business_id=$1 and id=$2 returning *`,
    [swap.businessId, swap.id, swap.toEmployeeId, swap.status, swap.reviewedBy ?? null],
  );
  return rows.length > 0 ? toShiftSwap(rows[0]!) : null;
}

/* -------------------------------------------------------------- inventory */

export async function listProducts(tx: Queryable, householdId: UUID, businessId: UUID): Promise<Product[]> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return [];
  // Archived products are excluded HERE rather than at each call site, because
  // every reader of this function — the shop screen, low-stock alerts, the
  // reconcile report, the sale path — means "products we still carry". A
  // retired product that reappeared in one of them would be a bug found in
  // production, and the one place it can never happen is the query.
  const { rows } = await tx.query<ProductRow>(
    `select * from product where business_id = $1 and archived_at is null order by sku asc`,
    [businessId],
  );
  return rows.map(toProduct);
}

export async function insertProduct(
  tx: Queryable, householdId: UUID, product: Omit<Product, 'id'>,
): Promise<Product | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, product.businessId))) return null;
  const { rows } = await tx.query<ProductRow>(
    `insert into product (business_id, sku, name, quantity_on_hand, reorder_point,
                          unit_cost_cents, unit_price_cents, category, barcode, supplier)
     values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,
    [product.businessId, product.sku, product.name, product.quantityOnHand, product.reorderPoint,
     product.unitCost, product.unitPrice, product.category ?? null, product.barcode ?? null,
     product.supplier ?? null],
  );
  const saved = toProduct(rows[0]!);
  await indexDocument(tx, {
    entity: 'product', id: saved.id, householdId, title: saved.name, body: saved.sku,
    businessId: saved.businessId,
  });
  return saved;
}

export async function saveProduct(tx: Queryable, householdId: UUID, product: Product): Promise<Product | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, product.businessId))) return null;
  const { rows } = await tx.query<ProductRow>(
    `update product set sku=$3, name=$4, quantity_on_hand=$5, reorder_point=$6,
                        unit_cost_cents=$7, unit_price_cents=$8, category=$9, barcode=$10, supplier=$11
      where business_id=$1 and id=$2 returning *`,
    [product.businessId, product.id, product.sku, product.name, product.quantityOnHand,
     product.reorderPoint, product.unitCost, product.unitPrice, product.category ?? null,
     product.barcode ?? null, product.supplier ?? null],
  );
  if (rows.length === 0) return null;
  const saved = toProduct(rows[0]!);
  await indexDocument(tx, {
    entity: 'product', id: saved.id, householdId, title: saved.name, body: saved.sku,
    businessId: saved.businessId,
  });
  return saved;
}

/**
 * Does anything in the ledger point at this product?
 *
 * Two different dangers, one question. `sale_item.product_id` is
 * `on delete restrict`, so a sold product cannot be deleted at all — the
 * database would raise, and a 500 is a poor way to say "this was sold".
 * `inventory_movement.product_id` is `on delete cascade`, which is worse: the
 * delete succeeds and takes every receive, adjustment and shrinkage row with
 * it, so `reconcileInventory` silently loses the drift it exists to find.
 */
export async function productHasHistory(
  tx: Queryable, householdId: UUID, businessId: UUID, productId: UUID,
): Promise<boolean> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return false;
  const { rows } = await tx.query<{ n: number }>(
    `select (
       (select count(*) from inventory_movement where business_id = $1 and product_id = $2) +
       (select count(*) from sale_item where product_id = $2)
     )::int as n`,
    [businessId, productId],
  );
  return Number(rows[0]?.n ?? 0) > 0;
}

/**
 * Retire a product that has been stocked or sold (migration 002).
 *
 * The row stays so the ledger keeps referring to something real; `listProducts`
 * stops returning it, and the search document goes, so every screen agrees it
 * is gone.
 */
export async function archiveProduct(
  tx: Queryable, householdId: UUID, businessId: UUID, productId: UUID, at: string,
): Promise<Product | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return null;
  const { rows } = await tx.query<ProductRow>(
    `update product set archived_at = coalesce(archived_at, $3)
      where business_id = $1 and id = $2 returning *`,
    [businessId, productId, at],
  );
  if (rows.length === 0) return null;
  await unindexDocument(tx, 'product', productId);
  return toProduct(rows[0]!);
}

/** Delete a product nothing references. Called only after `productHasHistory`. */
export async function deleteProduct(
  tx: Queryable, householdId: UUID, businessId: UUID, productId: UUID,
): Promise<boolean> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return false;
  const { rowCount } = await tx.query(
    `delete from product where business_id = $1 and id = $2`, [businessId, productId],
  );
  if (rowCount > 0) await unindexDocument(tx, 'product', productId);
  return rowCount > 0;
}

export async function insertMovement(
  tx: Queryable, householdId: UUID, movement: Omit<InventoryMovement, 'id'>,
): Promise<InventoryMovement | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, movement.businessId))) return null;
  const { rows } = await tx.query<MovementRow>(
    `insert into inventory_movement (business_id, product_id, kind, quantity_delta, at, unit_cost_cents, note)
     values ($1,$2,$3,$4,$5,$6,$7) returning *`,
    [movement.businessId, movement.productId, movement.kind, movement.quantityDelta,
     movement.at, movement.unitCost ?? null, movement.note ?? null],
  );
  return toMovement(rows[0]!);
}

export async function listMovements(
  tx: Queryable, householdId: UUID, businessId: UUID,
): Promise<InventoryMovement[]> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return [];
  const { rows } = await tx.query<MovementRow>(
    `select * from inventory_movement where business_id = $1 order by at asc, id asc`, [businessId],
  );
  return rows.map(toMovement);
}

/* ------------------------------------------------------------ sales/expenses */

export async function insertSale(tx: Queryable, householdId: UUID, sale: Omit<Sale, 'id'>): Promise<Sale | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, sale.businessId))) return null;
  const { rows } = await tx.query<SaleRow>(
    `insert into sale (business_id, at, tax_collected_cents, channel) values ($1,$2,$3,$4) returning *`,
    [sale.businessId, sale.at, sale.taxCollectedCents ?? null, sale.channel ?? null],
  );
  const saleId = rows[0]!.id;
  let line = 0;
  for (const item of sale.items) {
    line += 1;
    await tx.query(
      `insert into sale_item (sale_id, line_no, product_id, quantity, unit_price_cents)
       values ($1,$2,$3,$4,$5)`,
      [saleId, line, item.productId, item.quantity, item.unitPriceCents],
    );
  }
  return getSale(tx, householdId, saleId);
}

export async function getSale(tx: Queryable, householdId: UUID, saleId: UUID): Promise<Sale | null> {
  const { rows } = await tx.query<SaleRow>(
    `select s.* from sale s join business b on b.id = s.business_id
      where s.id = $1 and b.household_id = $2`,
    [saleId, householdId],
  );
  if (rows.length === 0) return null;
  const items = await tx.query<{ product_id: string; quantity: number; unit_price_cents: number }>(
    `select product_id, quantity, unit_price_cents from sale_item where sale_id = $1 order by line_no`,
    [saleId],
  );
  return toSale({ ...rows[0]!, items: items.rows });
}

export async function listSales(
  tx: Queryable, householdId: UUID, businessId: UUID, window?: { from: string; to: string },
): Promise<Sale[]> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return [];
  const { rows } = await tx.query<SaleRow>(
    `select * from sale
      where business_id = $1
        and ($2::timestamptz is null or at >= $2)
        and ($3::timestamptz is null or at < $3)
      order by at asc, id asc`,
    [businessId, window?.from ?? null, window?.to ?? null],
  );
  if (rows.length === 0) return [];

  const items = await tx.query<{ sale_id: string; product_id: string; quantity: number; unit_price_cents: number }>(
    `select sale_id, product_id, quantity, unit_price_cents from sale_item
      where sale_id = any($1::uuid[]) order by sale_id, line_no`,
    [rows.map((r) => r.id)],
  );
  const byId = new Map<string, typeof items.rows>();
  for (const item of items.rows) {
    const bucket = byId.get(item.sale_id);
    if (bucket) bucket.push(item);
    else byId.set(item.sale_id, [item]);
  }
  return rows.map((r) => toSale({ ...r, items: byId.get(r.id) ?? [] }));
}

export async function insertExpense(
  tx: Queryable, householdId: UUID, expense: Omit<Expense, 'id'>,
): Promise<Expense | null> {
  if (!(await assertBusinessInHousehold(tx, householdId, expense.businessId))) return null;
  const { rows } = await tx.query<ExpenseRow>(
    `insert into expense (business_id, at, vendor, category, amount_cents, description, receipt_attachment_id)
     values ($1,$2,$3,$4,$5,$6,$7) returning *`,
    [expense.businessId, expense.at, expense.vendor, expense.category, expense.amountCents,
     expense.description ?? null, expense.receiptAttachmentId ?? null],
  );
  const saved = toExpense(rows[0]!);
  await indexDocument(tx, {
    entity: 'expense', id: saved.id, householdId, title: saved.vendor,
    body: saved.category, at: saved.at, businessId: saved.businessId,
  });
  return saved;
}

export async function listExpenses(
  tx: Queryable, householdId: UUID, businessId: UUID, window?: { from: string; to: string },
): Promise<Expense[]> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return [];
  const { rows } = await tx.query<ExpenseRow>(
    `select * from expense
      where business_id = $1
        and ($2::timestamptz is null or at >= $2)
        and ($3::timestamptz is null or at < $3)
      order by at desc, id asc`,
    [businessId, window?.from ?? null, window?.to ?? null],
  );
  return rows.map(toExpense);
}

export async function totalReserved(tx: Queryable, householdId: UUID, businessId: UUID): Promise<number> {
  if (!(await assertBusinessInHousehold(tx, householdId, businessId))) return 0;
  const { rows } = await tx.query<{ total: number | string | null }>(
    `select coalesce(sum(amount_cents),0) as total from tax_reserve_entry where business_id = $1`,
    [businessId],
  );
  return Number(rows[0]?.total ?? 0);
}

export async function insertReserveEntry(
  tx: Queryable, householdId: UUID,
  input: { businessId: UUID; at: string; amountCents: number; note?: string },
): Promise<boolean> {
  if (!(await assertBusinessInHousehold(tx, householdId, input.businessId))) return false;
  await tx.query(
    `insert into tax_reserve_entry (business_id, at, amount_cents, note) values ($1,$2,$3,$4)`,
    [input.businessId, input.at, input.amountCents, input.note ?? null],
  );
  return true;
}

/* ---------------------------------------------------------- notifications */

export async function upsertNotifications(
  tx: Queryable,
  drafts: ReadonlyArray<Omit<Notification, 'id'>>,
): Promise<number> {
  let created = 0;
  for (const draft of drafts) {
    // `do nothing` is the anti-nagging guarantee: the unique index on
    // (household_id, dedupe_key) means regenerating from unchanged facts is a
    // no-op, and an already-read notification is never resurrected unread.
    const { rowCount } = await tx.query(
      `insert into notification (household_id, recipient_member_id, kind, channel, title, body,
                                 deliver_at, subject_entity, subject_id, dedupe_key)
       values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
       on conflict (household_id, dedupe_key) do nothing`,
      [draft.householdId, draft.recipientMemberId, draft.kind, draft.channel, draft.title,
       draft.body, draft.deliverAt, draft.subject?.entity ?? null, draft.subject?.id ?? null,
       draft.dedupeKey],
    );
    created += rowCount;
  }
  return created;
}

export async function listNotifications(
  tx: Queryable, householdId: UUID, memberId: UUID, now: string,
): Promise<Notification[]> {
  const { rows } = await tx.query<NotificationRow>(
    `select * from notification
      where household_id = $1
        and (recipient_member_id is null or recipient_member_id = $2)
        and read_at is null
        and deliver_at <= $3
      order by deliver_at desc, id asc`,
    [householdId, memberId, now],
  );
  return rows.map(toNotification);
}

export async function markNotificationRead(
  tx: Queryable, householdId: UUID, memberId: UUID, notificationId: UUID, at: string,
): Promise<boolean> {
  const { rowCount } = await tx.query(
    `update notification set read_at = coalesce(read_at, $4)
      where household_id = $1 and id = $3
        and (recipient_member_id is null or recipient_member_id = $2)`,
    [householdId, memberId, notificationId, at],
  );
  return rowCount > 0;
}

/* ---------------------------------------------------------------- audit */

export async function writeAudit(
  tx: Queryable,
  entry: {
    householdId: UUID; actorMemberId: UUID | null; action: string;
    entity: string; entityId: string; before?: unknown; after?: unknown;
  },
): Promise<void> {
  await tx.query(
    `insert into audit_log (household_id, actor_member_id, action, entity, entity_id, before, after)
     values ($1,$2,$3,$4,$5,$6,$7)`,
    [entry.householdId, entry.actorMemberId, entry.action, entry.entity, entry.entityId,
     entry.before === undefined ? null : JSON.stringify(entry.before),
     entry.after === undefined ? null : JSON.stringify(entry.after)],
  );
}

export async function recordAiAction(
  tx: Queryable,
  entry: { householdId: UUID; actorMemberId: UUID; proposal: unknown; verdict: string; executedAt?: string },
): Promise<void> {
  await tx.query(
    `insert into ai_action (household_id, actor_member_id, proposal, verdict, executed_at)
     values ($1,$2,$3,$4,$5)`,
    [entry.householdId, entry.actorMemberId, JSON.stringify(entry.proposal), entry.verdict,
     entry.executedAt ?? null],
  );
}
